version: "3.9"

services:
  backend:
    build:
      context: ./JobPositions-backend
      dockerfile: JobPositions/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - app-network

  frontend:
    build:
      context: ./job-positions-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
